# https://www.zaber.com/wiki/Manuals/X-LRQ-DEC
# https://www.zaber.com/wiki/Manuals/ASCII_Protocol_Manual
accel 	Axis 	Yes 	6.06+ 	Sets the acceleration used to modify the speed.
calibration.type 	Axis 	No 	6.24+ 	The type of calibration saved for the axis.
cloop.counts 	Axis 	Yes 	6.06+ 	The number of counts generated by the encoder for one full revolution.  int
cloop.displace.tolerance 	Axis 	Yes 	6.19+ 	The minimum deviation in the position of a stationary axis that will register as a displacement.
cloop.duration.max 	Axis 	Yes 	6.17+ 	The duration for attempting fine position correction.
cloop.mode 	Axis 	Yes 	6.06+ 	The closed-loop (slip, stall, and displacement detection and recovery) control mode.
cloop.stalltimeout 	Axis 	Yes 	6.06+ 	The amount of time to wait after a stall/displacement condition, in milliseconds.
cloop.steps 	Axis 	Yes 	6.06+ 	The number of full steps required for the motor to complete one revolution. int
comm.address 	Device 	Yes 	6.06+ 	The device address.
comm.alert 	Device 	Yes 	6.06+ 	The device will send alert messages when this setting is 1.
comm.checksum 	Device 	Yes 	6.06+ 	The device includes checksums in its messages if this setting is set to 1.
comm.protocol 	Device 	Yes 	6.06+ 	The communications protocol used by the device on the current interface.
comm.rs232.baud 	Device 	Yes 	6.06+ 	The baud rate used by RS232 Prev and Next interfaces.
comm.rs232.protocol 	Device 	Yes 	6.09+ 	The protocol used by RS232 Prev and Next interfaces.
comm.rs485.baud 	Device 	Yes 	6.09+ 	The baud rate used by RS485 interface.
comm.rs485.enable 	Device 	Yes 	6.09+ 	Enables the RS485 interface.
comm.rs485.protocol 	Device 	Yes 	6.09+ 	The protocol used by RS485 interface.
comm.usb.protocol 	Device 	Yes 	6.09+ 	The protocol used by the usb interface.
deviceid 	Device 	No 	6.06+ 	The device ID for the unit.
driver.current.hold 	Axis 	Yes 	6.06+ 	Current used to hold the motor in position, in 20 mA DC increments.
driver.current.max 	Axis 	No 	6.16+ 	Maximum legal value of driver.current.hold and driver.current.run.
driver.current.run 	Axis 	Yes 	6.06+ 	Current used to drive the motor, in 14.1 mA RMS (20 mA peak) increments.
driver.dir 	Axis 	Yes 	6.06+ 	Reverse the motor driver output direction.
driver.temperature 	Axis 	No 	6.06+ 	The current temperature of the axis driver, in degrees Celsius.
encoder.count 	Axis 	Yes 	6.06+ 	The recorded counts of the axis encoder.
encoder.count.calibrated 	Axis 	No 	6.24+ 	The calibrated counts of the axis encoder.
encoder.dir 	Axis 	Yes 	6.06+ 	Inverts the counting direction for the axis encoder.
encoder.error 	Axis 	No 	6.17+ 	Position error measured by encoder.
encoder.fault.type 	Axis 	Yes 	6.24+ 	The type of fault signal provided by the encoder.
encoder.filter 	Axis 	Yes 	6.06+ 	Enable and set up digital filtering of the encoder inputs.
encoder.index.count 	Axis 	Yes 	6.06+ 	The recorded counts of the axis encoder index pulse.
encoder.index.mode 	Axis 	Yes 	6.06+ 	The operating mode of the axis encoder index signal.
encoder.index.phase 	Axis 	Yes 	6.06+ 	The required phase for an index pulse to be counted.
encoder.mode 	Axis 	Yes 	6.06+ 	The operating mode of the axis encoder.
encoder.pos 	Axis 	No 	6.17+ 	Position measured by encoder.
filter.holderid 	Axis 	Yes 	6.22+ 	The ID of the installed filter holder.
force.average 	Axis 	Yes 	6.25+ 	Average force applied recently by the axis.
joy.debug 	Device 	Yes 	6.16+ 	Joystick debugging mode.
knob.dir 	Axis 	Yes 	6.06+ 	Sets the movement direction for the knob.
knob.distance 	Axis 	Yes 	6.06+ 	Sets how far the device moves with each step of the knob in displacement mode, in units of microsteps.
knob.enable 	Axis 	Yes 	6.06+ 	Disable the use of the knob when set to 0.
knob.force 	Axis 	Yes 	6.25+ 	The maximum force that can be reached using the knob in force mode.
knob.forceprofile 	Axis 	Yes 	6.25+ 	Sets the profile to be used per increment when in force mode.
knob.maxspeed 	Axis 	Yes 	6.06+ 	The maximum speed that can be reached using the knob in velocity mode.
knob.mode 	Axis 	Yes 	6.06+ 	Sets the mode of the manual control knob.
knob.speedprofile 	Axis 	Yes 	6.06+ 	Sets the profile to be used per increment when in velocity mode.
limit.approach.maxspeed 	Axis 	Yes 	6.06+ 	Maximum speed used when approaching a limit sensor.
limit.cycle.dist 	Axis 	Yes 	6.20+ 	The length of one full rotation.
limit.detect.decelonly 	Axis 	Yes 	6.06+ 	Deceleration used when stopping after a limit sensor has triggered.
limit.detect.maxspeed 	Axis 	Yes 	6.06+ 	Maximum speed used when moving away from a limit sensor.
limit.home.action 	Axis 	Yes 	6.06+ 	Automatic limit switch action.
limit.home.edge 	Axis 	Yes 	6.06+ 	Sensor edge to align action to.
limit.home.pos 	Axis 	Yes 	6.06+ 	The updated position of the sensor, when triggered.
limit.home.posupdate 	Axis 	Yes 	6.06+ 	Position update to occur when sensor is triggered.
limit.home.preset 	Axis 	Yes 	6.06+ 	The default position of the home sensor.
limit.home.state 	Axis 	No 	6.06+ 	The state of the home sensor.
limit.home.triggered 	Axis 	No 	6.06+ 	Whether the home sensor has been triggered previously.
limit.home.type 	Axis 	Yes 	6.06+ 	The type of home sensor connected.
limit.away.action 	Axis 	Yes 	6.06+ 	Automatic limit switch action.
limit.away.edge 	Axis 	Yes 	6.06+ 	Sensor edge to align action to.
limit.away.pos 	Axis 	Yes 	6.06+ 	The updated position of the sensor, when triggered.
limit.away.posupdate 	Axis 	Yes 	6.06+ 	Position update to occur when sensor is triggered.
limit.away.preset 	Axis 	Yes 	6.06+ 	The default position of the away sensor.
limit.away.state 	Axis 	No 	6.06+ 	The state of the home sensor.
limit.away.triggered 	Axis 	No 	6.06+ 	Whether the away sensor has been triggered previously.
limit.away.type 	Axis 	Yes 	6.06+ 	The type of away sensor connected.
limit.c.action 	Axis 	Yes 	6.06+ 	Automatic limit switch action.
limit.c.edge 	Axis 	Yes 	6.06+ 	Sensor edge to align action to.
limit.c.pos 	Axis 	Yes 	6.06+ 	The updated position of the sensor, when triggered.
limit.c.posupdate 	Axis 	Yes 	6.06+ 	Position update to occur when sensor is triggered.
limit.c.preset 	Axis 	Yes 	6.06+ 	The default position of the c limit sensor.
limit.c.state 	Axis 	No 	6.06+ 	The state of the c limit sensor.
limit.c.triggered 	Axis 	No 	6.06+ 	Whether the c limit sensor has been triggered previously.
limit.c.type 	Axis 	Yes 	6.06+ 	The type of c limit sensor connected.
limit.d.action 	Axis 	Yes 	6.06+ 	Automatic limit switch action.
limit.d.edge 	Axis 	Yes 	6.06+ 	Sensor edge to align action to.
limit.d.pos 	Axis 	Yes 	6.06+ 	The updated position of the sensor, when triggered.
limit.d.posupdate 	Axis 	Yes 	6.06+ 	Position update to occur when sensor is triggered.
limit.d.preset 	Axis 	Yes 	6.06+ 	The default position of the d limit sensor.
limit.d.state 	Axis 	No 	6.06+ 	The state of the d limit sensor.
limit.d.triggered 	Axis 	No 	6.06+ 	Whether the d limit sensor has been triggered previously.
limit.d.type 	Axis 	Yes 	6.06+ 	The type of d limit sensor connected.
limit.max 	Axis 	Yes 	6.06+ 	The maximum position the device can move to, measured in microsteps.
limit.min 	Axis 	Yes 	6.06+ 	The minimum position the device can move to, measured in microsteps.
limit.start.pos 	Axis 	Yes 	6.19+ 	Start up position of the axis.
limit.swapinputs 	Axis 	Yes 	6.06+ 	Reverses the limit positions by swapping the home and away sensors.
lockstep.numgroups 	Device 	No 	6.15+ 	The number of lockstep groups provided on the device.
lockstep.tolerance 	Axis 	Yes 	6.15+ 	The maximum twist distance between axes in a lockstep group before a stop and untwist occurs.
maxspeed 	Axis 	Yes 	6.06+ 	The maximum speed the device moves at.
motion.accelonly 	Axis 	Yes 	6.06+ 	Sets the acceleration used to increase the speed.
motion.decelonly 	Axis 	Yes 	6.06+ 	Sets the deceleration used when decreasing the speed.
motion.index.dist 	Axis 	Yes 	6.21+ 	The distance between consecutive index positions.
motion.index.num 	Axis 	No 	6.22+ 	The current index number.
peripheralid 	Axis 	Yes 	6.06+ 	The ID of the connected peripheral.
peripheral.serial 	Axis 	Yes 	6.24+ 	The serial number of the attached peripheral.
pos 	Axis 	Yes 	6.06+ 	The current absolute position of the device.    int
resolution 	Axis 	Yes 	6.06+ 	Microstep resolution    int
stream.numbufs 	Device 	No 	6.14+ 	The number of stream buffers provided in the device.
stream.numstreams 	Device 	No 	6.14+ 	The number of streams provided in the device.
system.access 	Device 	Yes 	6.06+ 	Sets the access level of the user.
system.axiscount 	Device 	No 	6.06+ 	The number of axes in the device.
system.current 	Device 	No 	6.06+ 	The current being drawn by the device and motors.
system.led.enable 	Device 	Yes 	6.06+ 	Enables the front panel LEDs.
system.serial 	Device 	No 	6.15+ 	The serial number of the device.
system.temperature 	Device 	No 	6.06+ 	The current temperature of the unit, in degrees Celsius.
system.voltage 	Device 	No 	6.06+ 	The voltage being applied to the device.
version 	Device 	No 	6.06+ 	The firmware version of the device.
version.build 	Device 	No 	6.17+ 	The build number of the device’s firmware.
virtual.numvirtual 	Device 	No 	6.18+ 	Number of virtual axes. 
